### ISSUE TITLE
deploys failing with error: marking resource as failed because no progress for 1m30s    

### ISSUE THREAD

**Issue by oppianmatt** [werf/werf#4642]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

1.2.122+fix1

### How to reproduce

Not sure how to reproduce but on our builds, the only thing that change was the werf version. 

Helm resources fail to converge with error:

```
ERROR: marking resource as failed because no progress for 1m30
```

* working version: werf is /root/.trdl/repositories/werf/releases/1.2.117+fix2/linux-amd64/bin/werf
* not working version: werf is /root/.trdl/repositories/werf/releases/1.2.122+fix1/linux-amd64/bin/werf

### Result

ERROR: marking resource as failed because no progress for 1m30

resources fail to update and deploy fials

### Expected result

resources to update as normal

**Comment by oppianmatt** [comment]
so that was in stable, tried using alpha similar problem but different timeout:

error: marking resource as failed because no activity for 4m0s 

it seems to happen for the following resource kinds:

* PodDisruptionBudget
* ServiceAccount
* Secret
* ConfigMap
* Service
* HorizontalPodAutoscaler
* Ingress

Looks like things that haven't changed during a deploy. But the statefulsets and deployments which have changed did update

```
    werf.io/release-channel: 1.2 alpha
    werf.io/version: v1.2.132
```

**Comment by ilya-lesikov** [comment]
@oppianmatt Hello, can you provide full log of `werf converge`? Don't forget to remove the sensitive parts. Also, I will need your full `werf converge` command with all flags and the result of `env | grep WERF_` just before `werf converge`, thanks.

**Comment by ilya-lesikov** [comment]
Reverted stable to the older version until this is fixed. Currently can't reproduce. Any additional context would be helpful.

**Comment by ilya-lesikov** [comment]
Fixed in https://github.com/werf/kubedog/pull/271. Backported to all release channels.

**Comment by ilya-lesikov** [comment]
If previous fix didn't work for someone, this should fix it https://github.com/werf/werf/pull/4671

**Comment by oppianmatt** [comment]
so was using rock-solid which was working until just now

but seeing how a fix was backported to all release channels will try another channel and report back, and if still happening will provide the logs as requested

**Comment by oppianmatt** [comment]
can confirm that rock-solid and stable I was getting the error, but I tried alpha and it was working

**Comment by ilya-lesikov** [comment]
Good. The last fix at https://github.com/werf/werf/pull/4671 backported up to the stable release channel just now.
